# Site settings
title: Kartenn
email: info@kartenn.es
description: > # this means to ignore newlines until "baseurl:"
  KARTENN Tecnologías para la gestión ambiental y territorial
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kartenn.es" # the base hostname & protocol for your site

company: Kartenn

brand:
  logo: img/kartenn.png
  text: Tecnologías para la gestión ambiental y territorial

#headers:
#- title: Kartenn
#  url: /
#- title: Contacto
#  url: #contacto

carrusel:
- img: img/carrusel/analisis.png
  description: Desarrollo de proyectos basados en sistemas de información geográfica y teledetección
- img: img/carrusel/batimetria_3d.png
  description: Promover el movimiento OpenData
- title: Moreiras
  img: img/carrusel/moreiras.png
  description: asfasf dsfasd fasfasdfas fasdfas asdfasdfsdfasdfasdf asdfasdf a
  href: #
  link: Pincha aquí

circles:
- title: Gestión Ambiental
  img: img/circulos/informe_gimena.png
  href: http://www.kartenn.es/proyectos/
  description: Elaboración de estratetias que permitan gestionar los recursos naturales y conservar el medio ambiente promoviendo el desarollo sostenible.
  link: Más información
- title: Gestión Territorial
  img: img/circulos/informe_gimena.png
  href: http://www.kartenn.es/proyectos/
  description: Conseguir un equilibrio adecuado para el desarrollo económico, crecimiento de la población, uso racional de los recursos y protección y conservación del ambiente. 
  link: Saber más
- title: Tecnologías Abiertas
  img: img/circulos/Esquema_aplicacion_vDRP.png
  href: http://www.kartenn.es/downloads/
  description: Desarrollo de sistemas ágiles, de bajo coste y accesibles promoviendo el "open data" (datos abiertos) ayudando a que clientes y socios liberen sus datos en la medida de lo posible.
  link: Desarrollos
- title: Formación
  img: img/circulos/formacion.png
  href: http://www.kartenn.es/publicaciones/
  description: Aumentar la base de usuarios de estas tecnologías y mejorar sus competencias, organizan actividades formativas (cursos y talleres) y contribuyendo con publicaciones científicas.
  link: Saber más

collections:
- features

# Build settings
markdown: kramdown
