# Site settings
title: Kartenn
email: info@kartenn.es
description: > # this means to ignore newlines until "baseurl:"
  KARTENN Tecnologías para la Gestión Ambiental y Territorial
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kartenn.es" # the base hostname & protocol for your site
company: Kartenn
terms: http://www.kartenn.es/quienes-somos/
contact: http://www.kartenn.es/noticias/
cookies: http://www.kartenn.es/politica-de-cookies/

brand:
  logo: img/kartenn.png
  text: Tecnologías para la gestión ambiental y territorial

# headers:
# - title: Kartenn
#   url: /

carrusel:
- img: img/carrousel/moreiras_filtro.jpg
  description: Proyectos para Gestión Territorial y Urbana
- img: img/carrousel/batimetria_filtro.jpg
  description: Sistemas de Información Geográfica y Teledetección
- img: img/carrousel/analisis_filtro.jpg
  description: Estrategias de Desarrollo Sostenible

circles:
- title: Gestión Ambiental
  img: img/circles/informe_gimena.png
  href: http://www.kartenn.es/proyectos/
  description: Elaboración de estrategias que permitan gestionar los recursos naturales y conservar el medio ambiente promoviendo el desarollo sostenible.
  link: Más información
- title: Gestión Territorial
  img: img/circles/morfonucleos.png
  href: http://www.kartenn.es/proyectos/
  description: Conseguir un equilibrio adecuado para el desarrollo económico, crecimiento de la población, uso racional de los recursos y protección y conservación del ambiente. 
  link: Saber más
- title: Tecnologías Abiertas
  img: img/circles/Esquema_aplicacion_vDRP.png
  href: http://www.kartenn.es/downloads/
  description: Promover el desarrollo de sistemas ágiles, de bajo coste y accesibles apoyando el movimiento "open data" (datos abiertos) en lo posible.
  link: Ver desarrollos
- title: Formación
  img: img/circles/formacion.png
  href: http://www.kartenn.es/formacionsig/
  description: Organización de actividades formativas (cursos y talleres) en Sistemas de Información Geográfica (SIG) y teledetección.
  link: Más información

collections:
- features

# Build settings
markdown: kramdown
